services:
  - type: web
    name: daily-earn-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false   # yaha Render dashboard me apna Telegram Bot Token daalna hoga
